gateway:
  # need to specify each hostname individually on the gateway
  # for cert-manager
  hostnames:
    - aifutureslab-hub-grafana.bids.berkeley.edu
    - aifutureslab-hub-prometheus.bids.berkeley.edu
    - aifutureslab-hub.bids.berkeley.edu
  config:
    provider:
      kubernetes:
        envoyService:
          annotations:
            # preserve ip when gateway service gets recreated
            cloud.google.com/l4-rbs: "enabled"
            networking.gke.io/load-balancer-ip-addresses: "demo-ingress"
grafana:
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: BIDS
      org_role: Viewer
    auth.basic:
      enabled: true
  route:
    main:
      hostnames:
        - aifutureslab-hub-grafana.bids.berkeley.edu
  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: https://aifutureslab-hub-prometheus.bids.berkeley.edu
          isDefault: true
          editable: false
prometheus:
  server:
    route:
      main:
        hostnames:
          - aifutureslab-hub-prometheus.bids.berkeley.edu
