# source: https://github.com/2i2c-org/jupyterhub-home-nfs/blob/main/examples/jupyterhub-nfs-volume.yaml
# Volume definition to set up a NFS volume for JupyterHub to store users' home directories.
apiVersion: v1
kind: PersistentVolume
metadata:
  name: "{{ .Release.Name }}-home-nfs-mount"
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: home-nfs.{{ .Release.Namespace }}.svc.cluster.local
    path: /
  mountOptions:
    # copy pasta from 2i2c deployment
    # note: this is their gcp config,
    # while they use different defaults on aws
    - soft
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-nfs-mount
spec:
  accessModes:
    - ReadWriteMany
  volumeName: "{{ .Release.Name }}-home-nfs-mount"
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
