[workspace]
authors = ["Min RK <benjaminrk@gmail.com>"]
channels = ["conda-forge", "bioconda"]
name = "user"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
install-opencode = "bash install-opencode.sh"

[dependencies]
python = "3.12.*"
pip = "*"
jupyterlab = ">=4.5.7,<5"
jupyter-ai = ">=3.0.0,<4"
matplotlib-base = "*"
scipy = "*"
altair = "*"
jupyterlab_code_formatter = "*"
ipywidgets = "*"
jupyter-book = "*"
# temporary: get hub prerelease from pypi
# jupyterhub-singleuser = "5.5.0"
jupyterlab-git = "*"
jupyter_server_documents = "*"
nb-cli = "*"
nodejs = "22.*"
pandas = "*"
geopandas = "*"
polars = "*"
pixi = "*"
mamba = "*"
curl = "*"
black = "*"
ruff = "*"
isort = "*"
gh = "*"
gh-scoped-creds = "*"
jq = "*"
jupyter-resource-usage = "*"
uv = "*"
jupyter-server-proxy = "*"
jupyter-myst-build-proxy = "*"
unzip = "*"
ipycytoscape = "*"
jupyter-vscode-proxy = "*"
code-server = ">=4"
jupyter-sshd-proxy = "*"

# lightcone-cli dependencies
# to get as much as we can from conda instead of pypi
dask = "*"
distributed = "*"
click = "*"
rich = "*"
# snakemake is on bioconda
snakemake = "*"
snakemake-interface-executor-plugins = "*"
rocrate = "*"
# astra-tools
rapidfuzz = "*"
pypdf = "*"
httpx = "*"
linkml-runtime = "*"
dask-gateway = "*"
jupyter-launcher-shortcuts = "*"
seaborn = "*"
plotly = "*"


[pypi-dependencies]
jupyter-ai-biorouter-acp = { path = "jupyter-ai-biorouter-acp" }
# temporary during prerelease
jupyterhub = "==6.0.0b2"
lightcone-cli = ">=0.4.0"
