jupyterhub:
  httpRoute:
    hostnames:
      - aifutureslab-hub.bids.berkeley.edu
  hub:
    config:
      JupyterHub:
        public_url: https://aifutureslab-hub.bids.berkeley.edu
      OAuthenticator:
        oauth_callback_url: https://aifutureslab-hub.bids.berkeley.edu/hub/oauth_callback
      GenericOAuthenticator_calnet:
        oauth_callback_url: https://aifutureslab-hub.bids.berkeley.edu/hub/oauth_callback
jupyterhub-home-nfs:
  gke:
    volumeId: projects/bids-jupyterhub/zones/us-central1-a/disks/hub-nfs-demo
