#ENC[AES256_GCM,data:ngfHPSApSTTkr9+NcaHSoGkV8hpgoPrGAiIFRp/GywMpY/ZCicWXVKmeuk0OTcaFBz8z7y80W8h7bwSPKwpWhnGRTCiSQwp8BPyP8Q==,iv:lOtQXv8/xhwMyTzTuMZ25ceptL5N9xMelyKP5xyu7Dc=,tag:9IlLEupV2yxrcqFlJP9b5w==,type:comment]
#ENC[AES256_GCM,data:d3c47V4R/QVyNV6NEjIfw91d5rAXXBydLOHge3iRplEjL/iM75RdlooiiXzjtfYp1egW,iv:4ketfbVN4GkzjXv3M8WNaD0m3RfniHsap1e8dKCRkPA=,tag://1PTeuazpigPY+M+dyYIA==,type:comment]
#ENC[AES256_GCM,data:vebc8Yd/wkKhL+yJz+5+PEYzxVn0uCv3UvX9+SWqC0RgGcLBgIP/rOtCpg/oqqPSm8jI/zqWV3rVkzS3RUIjOGKTKg1qrrZg53muZNVSPdI0vetkxs0=,iv:MBIY7oKMcBXZycKZ89mfUX6dri4Yu+do8Gm+RgIKZFA=,tag:4dsqTPIu4Ego1RV67z9+UA==,type:comment]
jupyterhub:
  hub:
    config:
      JupyterHub:
        cookie_secret: ENC[AES256_GCM,data:ErceKGXE0XRaGsKfW2/KXjGzLV+0GPMngeYVInGQwSSc0NZi2yj6nUDnfnoRdoSukGfclVnmTAaAu1+giby4zQ==,iv:sJ6hTOOaDuqRv9le2XJerIp7hYRcAVYkJuFxBQG/ntA=,tag:FWK+a0r7tQhXQKYDkpzbUA==,type:str]
      CryptKeeper:
        keys:
          - ENC[AES256_GCM,data:+tKh6qKko70w5k58LdTkXh14I3Gk+Snv2t0jk4bHKX/LXqzzkgloRTgfSJuCOa9tw/XyXAK8PFD4fDbp+TYVuw==,iv:B9iI4Ajkcjjry7HG0C0zxJSdkbDeNBQLEmmt+NRB14c=,tag:MOimxhw82EKmDWz2+ICbLw==,type:str]
      GitHubOAuthenticator:
        #ENC[AES256_GCM,data:74pFWc2WraXIJ1RZrdQ5r2XztFEULbXjUTtb5wXsgp+le5b07il9zyicK/DoU45jj0QCX4fPHfdKcJyVMUIgzU6Y4O6pU04=,iv:hFVeN/bBOJIwJKtvT+XQgZ46MNbriBYdAIXbctUICy8=,tag:HYsdqch4wmHymEJ1PwEX1w==,type:comment]
        #ENC[AES256_GCM,data:TM3N+aUHxLgCJZzes5G7QataonlK3CmMi3DWSokwcwSJbtlLSgH3izRSqgYAwYBrIHUKtDg=,iv:ZHWuYekbWRnbmZhIcbbNlyHE8ajK/u76EH2C5PQp6Zo=,tag:fObHgXjUmRrB4pG3C7H8XA==,type:comment]
        #ENC[AES256_GCM,data:S+49rRrF0HYSSFzrr2yVBfxhT0w6FAm/yfnfWbfHslzMBpgdSZeccam6THcxPz9+hV0tFD3FVg2U9+Eak+cgY1zA,iv:fe5poNBnN7HCDTTxqnJE5Pn9oO548UUUTsZHZwnE2vA=,tag:1ueuI9ysQBsjyIxPB56rkA==,type:comment]
        #ENC[AES256_GCM,data:Fl4fPZawqSUvGfc4LZfxhXPeGfzYJM7/hoOvXndKXdSbJIsRU5eIZA==,iv:Z02XktiHf7LZHDw03yx1F7mcD4uvwwR0cBvB0K30BtU=,tag:Dlbfbi6G13HAlmuYsdjY4g==,type:comment]
        client_id: ENC[AES256_GCM,data:ljapI3z0mnpXaLCiiTKAFSLTIHE=,iv:YK8Wntl++a2Vdq478rteem5A3VOY+NgyLUhsY8hwSHg=,tag:L/gYX4Wm11gRhwQLFXC4Gg==,type:str]
        client_secret: ENC[AES256_GCM,data:iPvK5rS6JWq1prlNb3GtZuRIh8ZIN17D+jd1dZtkOxbV5gtEYCDJAw==,iv:PJ055es71e0zp/Jvk/ORM77WhucVi1yvK9hkwjHZ82o=,tag:neiwd8ehnCUzsB8grDJFJw==,type:str]
    extraFiles:
      access:
        data:
          admin_users:
            - ENC[AES256_GCM,data:ETiKctg=,iv:DqljgSbM0ZCGiDDt9KXhsncoxaheYxGyzhN8w/tJHU0=,tag:Iqhidds8jb1Nkbxe9Ugplg==,type:str]
            - ENC[AES256_GCM,data:2szSUJOsACq/,iv:ErVXP5DyXBG1AmkxMs+wAuR53VFr7Dff9NE7QvUJY+I=,tag:rWJ8TribHuJ/p2thn3H2kQ==,type:str]
            - ENC[AES256_GCM,data:tHE3bh6TeHY=,iv:SvU0JSufb6OngmMVCJpxNrOuQWLuT4Izwkl1W6ALhDM=,tag:pqZrKeioSuZ3le3Mlf4WAg==,type:str]
          allowed_users:
            - ENC[AES256_GCM,data:H09x4gkhL44=,iv:tsYDQArG5CEYT4CdFtrDC5ViOcqQ2mIGkXzN5AY/NZU=,tag:7zgoeRsrnmdaevEzS406hA==,type:str]
            - ENC[AES256_GCM,data:uMXgWhc=,iv:8ENrPhFqXERqzxGH46SymyYjSeoYfw2hVTJMFbtmeQY=,tag:buOXMiCcKdKJ03k+fuQUjQ==,type:str]
            - ENC[AES256_GCM,data:wl3ZxzAchyTo,iv:kWwTqrNZJTkmhVy1502lutB9b685ZLF2Ho6WQl48F8c=,tag:fJ3xK3CZMK6gCSzYNJSG7g==,type:str]
            - ENC[AES256_GCM,data:L7AGyU0=,iv:rnAW4gsrAQC8eHv/HLf49yhnZ2pDl1yV+LBsVnmUtjg=,tag:Tw7rSEXY4SxyaQJcV96MRw==,type:str]
            - ENC[AES256_GCM,data:wh5TlDaT/vYGyEcgIyVN,iv:nIr7kW09D16E5o7Qr5Qy5OGKTeYceY5baW6ShP8gOLY=,tag:9wRtHfR9/j/ou+bIR1Fv3g==,type:str]
            - ENC[AES256_GCM,data:yqutX05+q9lUHA==,iv:36dFXaUuMgD/q2HnbAnUA8NdgTGH7s3guf5xnibcJsE=,tag:aWFHcAqzWBwDztDsEl4eWQ==,type:str]
          collaborations: {}
  singleuser:
    extraEnv:
      #ENC[AES256_GCM,data:z74m665LpmnoZfz8FxPKLrJ8Z6LX7ic3BcLHyLBvSFxcyDQxZWNs6JdFz6tNhjpgC4HgUZK+mAGH1OdiFBb76yxbiGuXOoBACg==,iv:jjdXJUhmAxDgpaISiF19vpMd5eqE/X+UT1MQw+iB3Ns=,tag:jEaez3fEiwJZXoIUD0DMxw==,type:comment]
      #ENC[AES256_GCM,data:o8L3BpkNesHdJmmmSTfd/zMMAHjPzd2oskIKVBop5xLNWCUtrVCEhpHmKVKc3zbt2BVfXN+SyuJ6mhbEimJ5vkuYDOw=,iv:v9TRffz09Ezo19v5z3ql5XtWuoU89sT9fyXjBhr5bzM=,tag:lwRf3CUwJsjsUjKlOxGwaw==,type:comment]
      OPENAI_API_KEY: ENC[AES256_GCM,data:tssEiIiQ7zolUlL282Es0XIfyi9zMvEu7WH2yE8OZS3/nKX4kdKTjJe2RS1KctPswjKzqbiccHCRKt0gd+wgO+0LZ994Sf7xi2YWLQPC7UY2NdF/j8Lhhqtao6bVMcMflbmQhyT4ShgQ5qYSRTcI39TqTWP/jrGouQeCAWvTMHwA1jkXEI9TNOpeG5bH3Shp69/6BvGXoa11FUBOgSGrswn0ptA=,iv:JnDyo6Kgm03f7+DbWZKqpX0bx0RncLwbHzAuPdEdkho=,tag:d1u7HVH1PNIqP62YjDKg+A==,type:str]
sops:
  gcp_kms:
    - created_at: "2026-09-08T02:51:43Z"
      enc: CiQA4YWzxgkJ5QyWdvFMtNG/hLXxvjRXali16JUB5hFZGnEQO6YSSQBSWm9NOM0L9fDNxsDN5tKDhXXe1/uxQBYrsnxHRA2fciokCEmDS1dZNUTo1nYS/oqBl3U5kPwJ36BqqKUAMfDq3v/+Clzg7YM=
      resource_id: projects/lightconehub/locations/global/keyRings/sops/cryptoKeys/sops-key
  lastmodified: "2026-09-08T02:51:44Z"
  mac: ENC[AES256_GCM,data:7zELqUO5NAFfYMv1wMJbfjIA9KV9woLtxW+8o5xsHr9TrCKQCFmOttYswuQ8CfkIasCLGotaFe7YIqW9xjsnl6wDpfY14HthTeeWJdgZh8+aWajr6nYkXdKFWTBd4sQ2b9XrcI1YIOQhbE20Elg5BNMKjw++tAxHtFMcpB/q3ds=,iv:F+jH1cawJbZneIx0KXRx9MzJDs/I+StN+Pjc0s4ONZk=,tag:NCaM/4Ay2rz2vR8Bph4/3A==,type:str]
  unencrypted_suffix: _unencrypted
  version: 3.13.3
