coreNodeSelector: &coreNodeSelector
  hub.jupyter.org/node-purpose: core
# workloads with persistent storage must go on hyperdisk-capable nodes
persistentNodeSelector: &persistentNodeSelector
  hub.jupyter.org/node-purpose: core
  disk-type.gke.io/hyperdisk-balanced: "true"
gateway:
  issuerName: letsencrypt-prod
  # need to specify each hostname individually on the gateway
  # for cert-manager
  hostnames: []
  config:
    # passthrough for EnvoyProxy config
    # https://gateway.envoyproxy.io/docs/tasks/operations/customize-envoyproxy/
    provider:
      type: Kubernetes
clusterIssuer:
  enabled: true
grafana:
  nodeSelector: *persistentNodeSelector
  grafana.ini:
    auth.anonymous:
      enabled: true
      org_name: BIDS
      org_role: Viewer
    auth.basic:
      enabled: true
  route:
    main:
      enabled: true
      parentRefs:
        - name: default
          namespace: support
  persistence:
    size: 2Gi
    enabled: true
    accessModes:
      - ReadWriteOnce
prometheus:
  nodeSelector: *coreNodeSelector
  nodeExporter:
    updateStrategy:
      type: RollingUpdate
  alertmanager:
    enabled: false
  pushgateway:
    enabled: false
  rbac:
    create: true
  server:
    nodeSelector: *persistentNodeSelector
    podLabels:
      hub.jupyter.org/network-access-hub: "true"
    route:
      main:
        enabled: true
        parentRefs:
          - name: default
            namespace: support
  kube-state-metrics:
    metricLabelsAllowlist:
      - pods=[app,component]
      - nodes=[*]
