name: Publish images
on:
  push:
    branches:
      - main
    paths:
      - images/**
      - .github/workflows/images.yaml
  pull_request:
    paths:
      - images/**
      - .github/workflows/images.yaml
env:
  # only publish from this repo, not forks
  PUBLISHING_REPO: BIDS/hub-deploy
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
jobs:
  push_to_registry:
    name: Publish container images
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
      attestations: write
      id-token: write
    services:
      # So that we can test this in PRs/branches
      local-registry:
        image: registry:2
        ports:
          - 5000:5000
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Should we push this image to a public registry?
        shell: python
        run: |
          import os
          repo = os.environ["GITHUB_REPOSITORY"]
          event = os.environ["GITHUB_EVENT_NAME"]
          ref = os.environ["GITHUB_REF"]
          if (
              repo == "${{ env.PUBLISHING_REPO }}"
              and event == "push"
              and (
                  ref.startswith("refs/tags/")
                  or ref == "refs/heads/main"
              )
          ):
              print(f"Publishing image to {os.environ['REGISTRY']}")
          else:
              # PR or fork, don't push
              print("Publishing image to local registry")
              with open(os.environ["GITHUB_ENV"], "a") as f:
                  f.write(f"REGISTRY=localhost:5000\n")
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=sha,prefix=
          images: ${{ env.REGISTRY }}/bids/aifutureshub/user
      - name: Login to the Container registry
        if: env.REGISTRY == 'ghcr.io'
        uses: docker/login-action@abd2ef45e78c5afb21d64d4ca52ee8550d9572c7 # v4.5.1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          context: images/user
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
      - name: Generate artifact attestation
        if: env.REGISTRY == 'ghcr.io'
        uses: actions/attest@v4.2.0
        with:
          subject-name: ${{ env.REGISTRY }}/bids/aifutureshub/user
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
